version: '3.6'
services:
  cfssl:
    image: blackducksoftware/blackduck-cfssl:1.0.28
    volumes:
      - cert-volume:/etc/cfssl
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh", "http://localhost:8888/api/v1/cfssl/scaninfo" ]
      interval: 30s
      timeout: 10s
      retries: 5
    user: 'cfssl:root'

  logstash:
    image: blackducksoftware/blackduck-logstash:1.0.38
    volumes:
      - log-volume:/var/lib/logstash/data
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh", "http://localhost:9600/" ] 
      interval: 30s
      timeout: 10s
      retries: 5
    user: 'logstash:root'

  postgres:
    image: blackducksoftware/blackduck-postgres:14-1.25
    volumes:
      - postgres96-data-volume:/bitnami/postgresql
      - postgres-conf-volume:/opt/bitnami/postgresql/conf
      - storage-volume:/tmp/uploads
    env_file: [blackduck-config.env]
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
    user: '1001:root'
    stop_grace_period: 60s
    deploy:
      restart_policy:
        condition: on-failure
        
  postgres-upgrader:
    image: blackducksoftware/blackduck-postgres-upgrader:14-1.4
    volumes:
      - postgres96-data-volume:/bitnami/postgresql
      - postgres-conf-volume:/opt/bitnami/postgresql/conf
    env_file: [blackduck-config.env]
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh" ]
      interval: 5s
      timeout: 5s
      retries: 30
    user: 'root:root'
    deploy:
      restart_policy:
        condition: none

volumes:
  cert-volume:
  postgres96-data-volume:
  postgres-conf-volume:
  log-volume:
  storage-volume:
