version: '3.1'
services:
  cfssl:
    image: blackducksoftware/hub-cfssl:4.6.1
    volumes:
      - cert-volume:/etc/cfssl
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh", "http://localhost:8888/api/v1/cfssl/scaninfo" ]
      interval: 30s
      timeout: 10s
      retries: 5
    user: 'cfssl:root'

  logstash:
    image: blackducksoftware/hub-logstash:4.6.1
    volumes:
      - log-volume:/var/lib/logstash/data
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh", "http://localhost:9600/" ] 
      interval: 30s
      timeout: 10s
      retries: 5
    user: 'logstash:root'

  postgres:
    image: blackducksoftware/hub-postgres:4.6.1
    links:
      - cfssl
      - logstash
    volumes:
      - postgres96-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "/usr/local/bin/docker-healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
    user: 'postgres:root'

volumes:
  cert-volume:
  postgres96-data-volume:
  log-volume:
