{{- $_ :=  set . "serviceName" "blackduck-authentication" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: authentication
  name: {{ .Release.Name }}-blackduck-authentication
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: port-8443
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "bd.selectorLabelsWithoutVersion" . | nindent 4 }}
    component: authentication
  type: ClusterIP
{{- if and .Values.enablePersistentStorage (not .Values.authentication.persistentVolumeClaimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "bd.labelsWithoutVersion" . | nindent 4 }}
    component: pvc
  name: {{ .Release.Name }}-blackduck-authentication
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.authentication.claimSize }}
  {{- if .Values.authentication.storageClass }}
  storageClassName: {{ .Values.authentication.storageClass }}
  {{- else if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass }}
  {{- end}}
  {{- if .Values.authentication.volumeName }}
  volumeName: {{ .Values.authentication.volumeName }}
  {{- end -}}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: authentication
  name: {{ .Release.Name }}-blackduck-authentication
  namespace: {{ .Release.Namespace }}
spec:
  {{- if eq .Values.status "Running" }}
  replicas: 1
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "bd.selectorLabelsWithoutVersion" . | nindent 6 }}
      component: authentication
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "bd.selectorLabels" . | nindent 8 }}
        component: authentication
      annotations:
        {{- include "bd.prometheus.common.annotations" . | nindent 8 }}
        checksum/blackduck-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/postgres-config: {{ include (print $.Template.BasePath "/postgres-config.yaml") . | sha256sum }}
        {{- if .Values.authentication.podAnnotations }}
        {{- range $key, $value := .Values.authentication.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      name: {{ .Release.Name }}-blackduck-authentication
    spec:
      {{- if .Values.enableInitContainer }}
      initContainers:
      {{- include "bd.datadog.java.initcontainer" . | indent 6 }}
      {{- include "bd.postgresql.up.check.initcontainer" . | indent 6 }}
      {{- end }}
      containers:
      - env:
        - name: HUB_MAX_MEMORY
          value: {{ include "computeHubMaxMemory" .Values.authentication }}
        {{- if .Values.authentication.hubMinMemory }}
        - name: HUB_MIN_MEMORY
          value: {{ .Values.authentication.hubMinMemory }}
        {{- end }}
        {{- include "bd.datadog.java.env" . | indent 8 }}
        - name: DD_ENABLED
          value: {{ .Values.datadog.enabled | quote }}
        - name: HUB_MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
          value: {{ .Values.metrics.enabled | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-db-config
        - configMapRef:
            name: {{ .Release.Name }}-blackduck-config
        {{- if .Values.authentication.registry }}
          {{- if .Values.authentication.imageTag }}
        image: {{ .Values.authentication.registry }}/blackduck-authentication:{{ .Values.authentication.imageTag }}
          {{- else }}
        image: {{ .Values.authentication.registry }}/blackduck-authentication:{{ .Values.imageTag }}
          {{- end}}
        {{- else }}
          {{- if .Values.authentication.imageTag }}
        image: {{ .Values.registry }}/blackduck-authentication:{{ .Values.authentication.imageTag }}
          {{- else }}
        image: {{ .Values.registry }}/blackduck-authentication:{{ .Values.imageTag }}
          {{- end}}
        {{- end}}
        {{- include "customImagePullPolicy" .Values.authentication | nindent 8 }}
        {{- include "authenticationStartupProbe" . | nindent 8 }}
        {{- include "authenticationLivenessProbe" . | nindent 8 }}
        name: authentication
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          {{- toYaml .Values.authentication.resources | nindent 12 }}
        {{- with .Values.authentication.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        volumeMounts:
        {{- include "bd.ale.volumemounts" . | indent 8 }}
        {{- include "bd.datadog.java.volumemount" . | indent 8 }}
        {{- include "bd.postgresql.secrets.volumemounts" . | indent 8 }}
        - mountPath: /opt/blackduck/hub/hub-authentication/ldap
          name: dir-authentication
        - mountPath: /opt/blackduck/hub/hub-authentication/security
          name: dir-authentication-security
        {{- with .Values.certAuthCACertSecretName }}
        - mountPath: /tmp/secrets/AUTH_CUSTOM_CA
          name: auth-custom-ca
          subPath: AUTH_CUSTOM_CA
        {{- end }}
        {{- include "common.volume.mount" . | indent 8 }}
      dnsPolicy: ClusterFirst
      {{- include "bd.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.authentication.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.authentication.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.authentication.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.authentication.podSecurityContext }}
      {{- with .Values.authentication.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- else }}
      {{- include "bd.podSecurityContext" . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-blackduck-service-account
      volumes:
      {{- include "bd.datadog.java.volume" . | indent 6 }}
      {{- include "authenticationPersistentStorage" . | nindent 6 }}
      {{- include "bd.postgresql.secrets.volumes" . | indent 6 }}
      - emptyDir: {}
        name: dir-authentication-security
      {{- if .Values.certAuthCACertSecretName }}
      - name: auth-custom-ca
        secret:
          defaultMode: 420
          secretName: {{ .Values.certAuthCACertSecretName }}
      {{- end }}
      {{- include "common.volumes" . | indent 6 }}
      {{- if .Values.enableApplicationLevelEncryption }}
      {{- include "bd.ale.volumes" . | indent 6 }}
      {{- end }}

{{- define "authenticationStartupProbe" -}}
{{- if .Values.enableLivenessProbe -}}
startupProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/hub-authentication/security/root.crt
    - /opt/blackduck/hub/hub-authentication/security/blackduck_system.crt
    - /opt/blackduck/hub/hub-authentication/security/blackduck_system.key
  failureThreshold: {{ mul .Values.maxWaitForSchemaUpdatesMinutes 2 }}
  initialDelaySeconds: 240
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "authenticationLivenessProbe" -}}
{{- if .Values.enableLivenessProbe -}}
livenessProbe:
  exec:
    command:
    - /usr/local/bin/docker-healthcheck.sh
    - https://127.0.0.1:8443/api/health-checks/liveness
    - /opt/blackduck/hub/hub-authentication/security/root.crt
    - /opt/blackduck/hub/hub-authentication/security/blackduck_system.crt
    - /opt/blackduck/hub/hub-authentication/security/blackduck_system.key
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
{{- end -}}
{{- end -}}

{{- define "authenticationPersistentStorage" -}}
{{- if .Values.enablePersistentStorage -}}
- name: dir-authentication
  persistentVolumeClaim:
    claimName: {{if .Values.authentication.persistentVolumeClaimName}} {{.Values.authentication.persistentVolumeClaimName}} {{else}} {{ .Release.Name }}-blackduck-authentication {{end}}
{{- else -}}
- emptyDir: {}
  name: dir-authentication
{{- end -}}
{{- end -}}
