---
apiVersion: v1
data:
  {{- include "enablePostgresSSL" . | nindent 2 }}
  HUB_POSTGRES_ADMIN: {{ .Values.postgres.adminUserName }}
  {{- if not .Values.postgres.isExternal }}
  HUB_POSTGRES_HOST: {{ .Release.Name }}-blackduck-postgres
  {{- else }}
  HUB_POSTGRES_HOST: {{ .Values.postgres.host }}
  {{- end }}
  HUB_POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  HUB_POSTGRES_USER: {{ .Values.postgres.userUserName }}
kind: ConfigMap
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: postgres
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    argocd.argoproj.io/hook: PreSync,PostSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: {{ .Release.Name }}-blackduck-db-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  HUB_POSTGRES_ADMIN_PASSWORD_FILE: {{ .Values.postgres.adminPassword | b64enc }}
  HUB_POSTGRES_USER_PASSWORD_FILE: {{ .Values.postgres.userPassword | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: postgres
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
  name: {{ .Release.Name }}-blackduck-db-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
