postgres:
  resources:
    requests:
      cpu: "2000m"
      memory: "8192Mi"

jobrunner:
  replicas: 4
  hubMaxMemory: "6144m"
  maxPeriodicThreads: 4
  maxPeriodicPrefetch: 2
  maxOndemandThreads: 12
  maxOndemandPrefetch: 8
  resources:
    limits:
      cpu: "1000m"
      memory: "7168Mi"

scan:
  replicas: 2
  hubMaxMemory: "2048m"
  resources:
    limits:
      memory: "2560Mi"

webapp:
  hubMaxMemory: "4096m"
  resources:
    requests:
      cpu: "2000m"
    limits:
      memory: "5120Mi"

webserver:
  resources:
    limits:
      memory: "2048Mi"

webui:
  resources:
    requests:
      cpu: "500m"
    limits:
      cpu: "1000m"
      memory: "640Mi"

bomengine:
  replicas: 2
  hubMaxMemory: "6144m"
  resources:
    requests:
      memory: "1536Mi"
    limits:
      memory: "7168Mi"

matchengine:
  replicas: 2
  hubMaxMemory: "6144m"
  resources:
    requests:
      memory: "1536Mi"
      cpu: "500m"
    limits:
      memory: "7168Mi"
      cpu: "1000m"
