kind: List
apiVersion: v1
items:
##
# Put external postgres configuration here, if you have one.
##
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jobrunner
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jobrunner
        tier: jobrunner
    template:
      metadata:
        name: jobrunner
        labels:
          app: jobrunner
          tier: jobrunner
      spec:
        volumes:
        - name: db-passwords
          secret:
            secretName: db-creds
            items:
            - key: blackduck
              path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            - key: blackduck_user
              path: HUB_POSTGRES_USER_PASSWORD_FILE
        containers:
        - name: jobrunner
          volumeMounts:
          - name: db-passwords
            mountPath: /tmp/secrets
          image: blackducksoftware/hub-jobrunner:4.8.3
          name: jobrunner
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 4608M
            limits:
              cpu: 1
              memory: 4608M
          env:
          - name: HUB_MAX_MEMORY
            valueFrom:
              configMapKeyRef:
                name: hub-config-resources
                key: jobrunner-mem
          envFrom:
          - configMapRef:
              name: hub-config
          - configMapRef:
              name: hub-db-config
          - configMapRef:
              name: hub-db-config-granular
          - secretRef:
              name: hub-proxy-pass
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webserver
        tier: webserver
    template:
      metadata:
        name: webserver
        labels:
          app: webserver
          tier: webserver
      spec:
        volumes:
        - name: dir-webserver
          emptyDir: {}
        # Uncomment this line to add a custom TLS Certificate for the web server.
        # - name: nginx-certs
        #   secret:
        #     secretName: nginx-certs
        #     items:
        #     - key: WEBSERVER_CUSTOM_CERT_FILE
        #       path: WEBSERVER_CUSTOM_CERT_FILE
        #     - key: WEBSERVER_CUSTOM_KEY_FILE
        #       path: WEBSERVER_CUSTOM_KEY_FILE
        containers:
        - name: webserver
          image: blackducksoftware/hub-nginx:4.8.3
          envFrom:
          - configMapRef:
              name: hub-config
          resources:
            requests:
              memory: 512M
            limits:
              memory: 512M
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://localhost:8443/health-checks/liveness
                - /opt/blackduck/hub/webserver/security/root.crt
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            protocol: TCP
          volumeMounts:
          - name: dir-webserver
            mountPath: "/opt/blackduck/hub/webserver/security"
          # Uncomment this line to add a custom TLS Certificate for the web server.
          #- name: nginx-certs
          #  mountPath: "/tmp/secrets"
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: webapp-logstash
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: webapp-logstash
        tier: webapp-logstash
    template:
      metadata:
        name: webapp-logstash
        labels:
          app: webapp-logstash
          tier: webapp-logstash
      spec:
        volumes:
        - emptyDir: {}
          name: dir-webapp
        - emptyDir: {}
          name: dir-logstash
        - name: db-passwords
          secret:
            secretName: db-creds
            items:
            - key: blackduck
              path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            - key: blackduck_user
              path: HUB_POSTGRES_USER_PASSWORD_FILE
        containers:
        - name: webapp
          resources:
            requests:
              cpu: 1
              memory: 3072M
            limits:
              cpu: 1
              memory: 3072M
          image: blackducksoftware/hub-webapp:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://127.0.0.1:8443/api/health-checks/liveness
                - /opt/blackduck/hub/hub-webapp/security/root.crt
            initialDelaySeconds: 360 # We need to figure out why this takes so long.
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          - configMapRef:
              name: hub-db-config
          - configMapRef:
              name: hub-db-config-granular
          - secretRef:
              name: hub-proxy-pass
          env:
          - name: HUB_MAX_MEMORY
            valueFrom:
              configMapKeyRef:
                name: hub-config-resources
                key: webapp-mem
          volumeMounts:
          - name: db-passwords
            mountPath: /tmp/secrets
          - mountPath: "/opt/blackduck/hub/hub-webapp/security"
            name: dir-webapp
          - mountPath: "/opt/blackduck/hub/logs"
            name: dir-logstash
          ports:
          - containerPort: 8443
            protocol: TCP
        - image: blackducksoftware/hub-logstash:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:9600/
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          name: logstash
          resources:
            requests:
              memory: 1G
            limits:
              memory: 1G
          volumeMounts:
          - mountPath: "/var/lib/logstash/data"
            name: dir-logstash
          ports:
          - containerPort: 5044 # filebeat
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: documentation
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: documentation
    template:
      metadata:
        name: documentation
        labels:
          app: documentation
      spec:
        containers:
        - image: blackducksoftware/hub-documentation:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://127.0.0.1:8443/hubdoc/health-checks/liveness
                - /opt/blackduck/hub/hub-documentation/security/root.crt
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          name: documentation
          resources:
            limits:
              memory: "512M"
            requests:
              memory: "512M"
          ports:
          - containerPort: 8443
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: solr
  spec:
    selector:
      matchLabels:
        app: solr
        tier: solr
    replicas: 1
    template:
      metadata:
        name: solr
        labels:
          app: solr
          tier: solr
      spec:
        volumes:
        - name: solr-dir
          emptyDir: {}
        containers:
        - name: solr
          volumeMounts:
          - mountPath: /opt/blackduck/hub/solr/cores.data
            name: solr-dir
          resources:
            requests:
              memory: "640M"
            limits:
              memory: "640M"
          image: blackducksoftware/hub-solr:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:8983/solr/project/admin/ping?wt=json
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          ports:
          - containerPort: 8983
            protocol: TCP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: registration
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: registration
        tier: registration
    template:
      metadata:
        name: registration
        labels:
          app: registration
          tier: registration
      spec:
        volumes:
        - emptyDir: {}
          name: dir-registration
        containers:
        - image: blackducksoftware/hub-registration:4.8.3
          envFrom:
          - configMapRef:
              name: hub-config
          - secretRef:
              name: hub-proxy-pass
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://localhost:8443/registration/health-checks/liveness
                - /opt/blackduck/hub/hub-registration/security/root.crt
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: "640M"
            limits:
              memory: "640M"
          name: registration
          ports:
          - containerPort: 8443
            protocol: TCP
          volumeMounts:
          - mountPath: "/opt/blackduck/hub/hub-registration/config"
            name: dir-registration
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: zookeeper
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: zookeeper
        tier: zookeeper
    template:
      metadata:
        name: zookeeper
        labels:
          app: zookeeper
          tier: zookeeper
      spec:
        volumes:
        - emptyDir: {}
          name: dir-zookeeper-data
        - emptyDir: {}
          name: dir-zookeeper-datalog
        containers:
        - name: zookeeper
          image: blackducksoftware/hub-zookeeper:4.8.3
          envFrom:
          - configMapRef:
              name: hub-config
          livenessProbe:
            exec:
              command:
                - zkServer.sh
                - status
                - /opt/blackduck/zookeeper/conf/zoo.cfg
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 384M
            limits:
              memory: 384M
          ports:
          - containerPort: 2181
            protocol: TCP
          volumeMounts:
            - mountPath: "/opt/blackduck/zookeeper/data"
              name: dir-zookeeper-data
            - mountPath: "/opt/blackduck/zookeeper/datalog"
              name: dir-zookeeper-datalog
- apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
  spec:
    ports:
    - name: 2181-tcp
      protocol: TCP
      port: 2181
      targetPort: 2181
    selector:
      app: zookeeper
  status:
    loadBalancer: {}
- apiVersion: v1
# Delete this service and user 'webserver' instead
  kind: Service
  metadata:
    name: nginx-webapp-logstash
  spec:
    ports:
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 8443
    selector:
      app: webserver
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: webserver
  spec:
    ports:
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 8443
    selector:
      app: webserver
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: webapp
  spec:
    ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: webapp-logstash
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: logstash
  spec:
    ports:
    - name: 4560-tcp
      protocol: TCP
      port: 4560
      targetPort: 4560
    - name: 5044-tcp-filebeat
      protocol: TCP
      port: 5044
      targetPort: 5044
    selector:
      app: webapp-logstash
- apiVersion: v1
  kind: Service
  metadata:
    name: solr
  spec:
    ports:
    - name: 8983-tcp
      protocol: TCP
      port: 8983
      targetPort: 8983
    selector:
      app: solr
- apiVersion: v1
  kind: Service
  metadata:
    name: registration
  spec:
    ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: registration
- apiVersion: v1
  kind: Service
  metadata:
    name: documentation
  spec:
    ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: documentation
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hub-scan
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hub-scan
    template:
      metadata:
        name: hub-scan
        labels:
          app: hub-scan
      spec:
        volumes:
        - emptyDir: {}
          name: dir-scan
        - name: db-passwords
          secret:
            secretName: db-creds
            items:
            - key: blackduck
              path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            - key: blackduck_user
              path: HUB_POSTGRES_USER_PASSWORD_FILE
        containers:
        - name: hub-scan
          image: blackducksoftware/hub-scan:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://127.0.0.1:8443/api/health-checks/liveness
                - /opt/blackduck/hub/hub-scan/security/root.crt
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          - configMapRef:
              name: hub-db-config
          - configMapRef:
              name: hub-db-config-granular
          env:
          -  name: HUB_MAX_MEMORY
             valueFrom:
               configMapKeyRef:
                 name: hub-config-resources
                 key: scan-mem
          name: hub-scan
          volumeMounts:
          - mountPath: "/opt/blackduck/hub/hub-scan/security"
            name: dir-scan
          - name: db-passwords
            mountPath: /tmp/secrets
          resources:
            limits:
              memory: 2560M
            requests:
              memory: 2560M
          ports:
          - containerPort: 8443
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: scan # this is the default service name the hub looks for.
  spec:
    ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: hub-scan
  status:
    loadBalancer: {}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hub-authentication
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hub-authentication
    template:
      metadata:
        labels:
          app: hub-authentication
        name: hub-authentication
      spec:
        volumes:
        - emptyDir: {}
          name: dir-authentication
        - name: db-passwords
          secret:
            secretName: db-creds
            items:
            - key: blackduck
              path: HUB_POSTGRES_ADMIN_PASSWORD_FILE
            - key: blackduck_user
              path: HUB_POSTGRES_USER_PASSWORD_FILE
        containers:
        - image: blackducksoftware/hub-authentication:4.8.3
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://127.0.0.1:8443/api/health-checks/liveness
                - /opt/blackduck/hub/hub-authentication/security/root.crt
            initialDelaySeconds: 240
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: hub-config
          - configMapRef:
              name: hub-db-config
          - configMapRef:
              name: hub-db-config-granular
          - secretRef:
              name: hub-proxy-pass
          env:
          - name: HUB_MAX_MEMORY
            value: 512m
          name: hub-authentication
          volumeMounts:
          - mountPath: "/opt/blackduck/hub/hub-authentication/security"
            name: dir-authentication
          - name: db-passwords
            mountPath: /tmp/secrets
          resources:
            limits:
              memory: "1G"
            requests:
              memory: "1G"
          ports:
          - containerPort: 8443
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: authentication # this is the default service name the hub looks for.
  spec:
    ports:
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      app: hub-authentication
  status:
    loadBalancer: {}
